### PR TITLE
fix: don't try to look in home_tree if not available

### LINKED ISSUE #1004: luarocks 3.1.0: invalid value (boolean) at index 1 in table for 'concat' in dir.lua
I installed luarocks 3.1.0 today and got the following error when I want to install a rock:
```
/usr/local/bin/lua: /usr/local/share/lua/5.3/luarocks/core/dir.lua:23: invalid value (boolean) at index 1 in table for 'concat'
stack traceback:
	[C]: in function 'table.concat'
	/usr/local/share/lua/5.3/luarocks/core/dir.lua:23: in function 'luarocks.core.dir.path'
	/usr/local/share/lua/5.3/luarocks/cmd.lua:160: in upvalue 'get_lua_version'
	/usr/local/share/lua/5.3/luarocks/cmd.lua:287: in function 'luarocks.cmd.run_command'
	/usr/local/bin/luarocks:38: in main chunk
	[C]: in ?
```
It only happens if I want to install the rock globally. `--local` or project-wise install is working fine.

Fast debugging resulted in recognizing that the last call to `dir.path()` in `dir.lua` has a boolean as first argument:
```
false	.luarocks
```
I patched `dir.path()` the following way to get it work:
```diff
18c18
<    while t[1] == "" do
---
>    while t[1] == "" or type(t[1]) ~= "string" do
```

### PR DESCRIPTION
**Pull request by daurnimator**
Fix #1004

### CODE REVIEW

File: src/luarocks/cmd.lua [hunk 1]
```diff
@@ -156,15 +156,19 @@ local function get_lua_version(flags)
...
-   local dirs = {
-      dir.path(cfg.home_tree, ".luarocks"),
-      cfg.sysconfdir,
-   }
+   local dirs = {}
+   local next_i = 1
    if flags["project-tree"] then
-      table.insert(dirs, 1, dir.path(flags["project-tree"], "..", ".luarocks"))
+      dirs[next_i] = dir.path(flags["project-tree"], "..", ".luarocks")
+      next_i = next_i + 1
```
Comment (hishamhm) [inline src/luarocks/cmd.lua]: why not just use `table.insert` instead of `dirs[next_i]`? I only ask to make sure I'm not missing anything here.
